export const URL = {
  home: '/',
  login: '/login',
  address: '/address',
  menu: '/menu',
  offer: '/offer',
  blog: '/blog',
  gallery: '/gallery',
  contact: '/contact',
  booking: '/booking',
  blogdetails: '/blogdetails',
  profile: {
    information: '/profile/information',
    bookinghistory: '/profile/bookinghistory',
  },
  admin: {
    dashboard: '/admin',
    user: '/admin/user',
    branch: '/admin/branch',
    booking: '/admin/booking',
    blog: '/admin/blog',
    dish: '/admin/dish',
    gallery: '/admin/gallery',
    report: '/admin/report',
  },
};
